import './globals.css'
import { cn } from '@/lib/utils'
import { Inter } from 'next/font/google'
import Providers from '@/components/Providers'
import Navbar from '@/components/Navbar'
import { Toaster } from '@/components/ui/Toast'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={cn('bg-slate-50 text-slate-900 antialiased ', inter.className)}>
      <body className='min-h-screen bg-slate-100 dark:bg-slate-900'>
        <Providers>{children}
        <Toaster position='bottom-right'/>
          {/*@ts-expect-error Server Component*/}
        <Navbar />
        </Providers>
        <div className='h-40 md:hidden'></div>
      </body>
    </html>
  )
}
